### ISSUE TITLE
Significant increase in Akka.NET startup time

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/Cluster.WebCrawler#82]
After upgrading to Akka.NET v1.4.1, the amount of time it takes for the Cluster.WebCrawler containers to start up is significantly higher - from ~2s to ~33s.

We're going to need to benchmark this to see what's going on.

**Comment by Zetanova** [comment]
I am using IHostedService since beta over 2 years ago and had not this issues.

Tip:
I am using a startup service registered last to delay the completion of the startup process until the cluster and other dependencies are ready/healthy.

**Comment by Aaronontheweb** [comment]
@Zetanova so that big increase in startup time was correlated back to some huge inefficiencies in stand-alone HOCON: https://getakka.net/community/whats-new/akkadotnet-v1.4.html#post-mortem-stand-alone-hocon

We ultimately rolled that entire initiative back because it was clear that the problems were unresolvable in stand-alone HOCON without rearchitecting it. Problem basically came down to coupling the builder / input types to output types, when two totally separate data structures should be used.

I should close this issue then - WebCrawler starts fine on its own now.
